version: '2'
services:
  demoapp-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/DemoApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=DemoApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
